services:
  streamlit-app:
    build:
      context: ./Apps/chatbot_ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./Apps/chatbot_ui/src:/app/src

  api:
    build:
      context: ./Apps/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - QDRANT_URL=http://qdrant:6333
    restart: unless-stopped
    depends_on:
      - qdrant
    volumes:
      - ./Apps/api/src:/app/src

  items-mcp:
    build:
      context: ./Apps/items_Mcp
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - QDRANT_URL=http://qdrant:6333
    restart: unless-stopped
    depends_on:
      - qdrant
    volumes:
      - ./Apps/items_Mcp/src:/app/src

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: langgraph_db
      POSTGRES_USER: langgraph_user
      POSTGRES_PASSWORD: langgraph_password
      PGDATA: /var/lib/postgresql/data/pqdata
    restart: unless-stopped
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data


volumes:
  qdrant_storage:
